content_folder = ['matinales']
relative_build_url = "/"
absolute_build_url = "https://gautoz.cool/"
build_folder = "docs/"
assets_folder = "assets/"
medias_folder = "medias/"
template_file = "partials/main.html"
template_nav = "partials/nav.html"
rss_template = "partials/rss.xml"
rss_item_template = "partials/item.xml"
name_of_site = "Chez Gautoz"
site_meta_description = "Chez Gautoz c'est du stream jeu vidéo en tout décontraction."
twitter_name = "@gautoz"
home_name = "Accueil"
see_all = "Voir plus"
go_back = "Revenir à"
date_format = "EU"  # Choose between EU day-month-year or ISO year-mont-day
flat_build = False # True or False, if True, all files will be written in the root of the website